
$mainMod = ALT
bind = $mainMod, W, exec, killall waybar; waybar
bind = $mainMod, Q, killactive,
bind = $mainMod, T, exec, alacritty
bind = $mainMod, P, exec, librewolf -p
bind = $mainMod, F4, killactive
bind = CTRL $mainMod, backspace, exit
bind = $mainMod, D, exec, doublecmd
bind = $mainMod, E, togglefloating
bind = $mainMod, L, exec, hyprpicker --autocopy --format=hex
bind = $mainMod, I, exec, rider ~/.config/dotfiles.sln
bind = $mainMod, Tab, exec, hyprctl dispatch workspace unity
bind = $mainMod, Tab, exec, curl http://localhost:13131/dm/refresh
bind = $mainMod, Return, fullscreen, 1
bind = SUPER, Return, fullscreen, 2
bind = SUPER, L, exec, pactl set-sink-mute @DEFAULT_SINK@ 1 && hyprlock

bind =              , Print, exec, slurp | grim -g - - | wl-copy
bind = CTRL,              P, exec, slurp | grim -g - - | wl-copy
bind =      $mainMod, Print, exec, env XDG_CURRENT_DESKTOP=sway flameshot gui --path ~/Downloads/temp.png --clipboard
bind = CTRL $mainMod,     P, exec, env XDG_CURRENT_DESKTOP=sway flameshot gui --path ~/Downloads/temp.png --clipboard

#bind = SHIFT_L, 133, exec, zsh ~/.config/hypr/scripts/toggle_kb_layout.zsh

bind = $mainMod, F11, exec, alacritty --title nvtop --command nvtop
bind = $mainMod, F12, exec, alacritty --title btop --command btop
bind = $mainMod, F2, exec, zsh -c "source ~/.zshrc; type_ds"
bind = $mainMod, F3, exec, zsh -c "source ~/.zshrc; type_dh"
bindr = SUPER,  64, exec, killall wofi || wofi --show drun
bindr = SUPER, 133, exec, killall wofi || wofi --show drun
bind = SUPER, D, workspace, name:desktop
bindm = $mainMod, mouse:274, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind =, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind =, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind =, XF86AudioStop, exec, zsh ~/.config/hypr/scripts/mpris/stop.zsh
bind =, XF86AudioPlay, exec, zsh ~/.config/hypr/scripts/mpris/play-pause.zsh
bind =, XF86AudioNext, exec, zsh ~/.config/hypr/scripts/mpris/next.zsh
bind =, XF86AudioPrev, exec, zsh ~/.config/hypr/scripts/mpris/previous.zsh
bind = CTRL $mainMod, W, workspace, name:audio

bind = $mainMod, Z, workspace, name:audio
bind = $mainMod, X, workspace, name:comm
bind = $mainMod, C, workspace, name:code
bind = $mainMod, V, workspace, name:unity
bind = $mainMod, V, exec, curl http://localhost:13131/dm/refresh
bind = $mainMod, G, workspace, name:gk
bind = $mainMod, G, exec, curl http://localhost:13131/dm/refresh
bind = $mainMod, B, workspace, name:gaming
bind = $mainMod, N, workspace, name:security
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = CTRL SHIFT, Z, movetoworkspace, name:audio
bind = CTRL SHIFT, X, movetoworkspace, name:comm
bind = CTRL SHIFT, C, movetoworkspace, name:code
bind = CTRL SHIFT, V, movetoworkspace, name:unity
bind = CTRL SHIFT, G, movetoworkspace, name:gk
bind = CTRL SHIFT, B, movetoworkspace, name:gaming
bind = CTRL SHIFT, N, movetoworkspace, name:security
bind = CTRL SHIFT, 1, movetoworkspace, 1
bind = CTRL SHIFT, 2, movetoworkspace, 2
bind = CTRL SHIFT, 3, movetoworkspace, 3
bind = CTRL SHIFT, 4, movetoworkspace, 4
bind = CTRL SHIFT, 5, movetoworkspace, 5
bind = CTRL SHIFT, 6, movetoworkspace, 6
bind = CTRL SHIFT, 7, movetoworkspace, 7
bind = CTRL SHIFT, 8, movetoworkspace, 8
bind = CTRL SHIFT, 9, movetoworkspace, 9
bind = CTRL SHIFT, 0, movetoworkspace, 10